services:
  frontend:
    build: ./frontend
    image: pmp-ctf-dora001-frontend
    ports:
      - "18084:8080"
    environment:
      - BACKEND_URL=http://backend:8081
      - CORE_URL=http://core:8082
    depends_on:
      - backend
      - core
    networks:
      - dora001-net

  backend:
    build: ./backend
    image: pmp-ctf-dora001-backend
    ports:
      - "18081:8081"
    environment:
      - CORE_URL=http://core:8082
    depends_on:
      - core
    networks:
      - dora001-net

  core:
    build: ./core
    image: pmp-ctf-dora001-core
    ports:
      - "18082:8082"
    networks:
      - dora001-net

networks:
  dora001-net:
    driver: bridge
